---
framework: jest

preRun:
  command:
    - npm install
    - npm run prepare
    - npm -v

postMerge:
  pattern:
    - "**/test/unit/*.spec.ts"
    - "/test/jest/unit/*.spec.ts"
    - "/test/jest/unit/**/*.spec.ts"
